Dev sergionx
MetroTech-UNIMET/Metro-Grama pull request #6
Opened 2024-03-15 17:48 UTC by Sergionx

2024-03-15 18:29 UTC, Stolkerve requested changes
No puede hacer merge por que me sale este error:
error TS2307: Cannot find module '@radix-ui/react-slot' or its corresponding type declarations
Estuve viendo en el package.json y no encontre el radix, @Sergionx ponlo porfa

2024-03-15 19:22 UTC, Sergionx commented
> No puede hacer merge por que me sale este error: error TS2307: Cannot find module '@radix-ui/react-slot' or its corresponding type declarations Estuve viendo en el package.json y no encontre el radix, @Sergionx ponlo porfa



> No puede hacer merge por que me sale este error: error TS2307: Cannot find module '@radix-ui/react-slot' or its corresponding type declarations Estuve viendo en el package.json y no encontre el radix, @Sergionx ponlo porfa

Lo quité porque al final no use nada de radix por ahora dado que cree mi propio componente List, aún así lo vuelvo a poner?

2024-03-15 19:26 UTC, Stolkerve commented
> Lo quité porque al final no use nada de radix por ahora dado que cree mi propio componente List, aún así lo vuelvo a poner?

Si lo puedes volver a poner, pero tiene que estar en el package.json, en tal sube un commit borrandolo o instalandolo.

2024-03-16 15:47 UTC, Stolkerve approved these changes

2024-03-16 15:47 UTC, merged